development:
  sessions:
    default:
      database: kc_score_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: kc_score_test
      hosts:
        - localhost:27017